2018-05-09 17:00:33,172 ERROR: Exception on /user/susan [GET] [in /home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/krupni/microblog/app1/routes.py", line 115, in user
    page = request.agrs.get('page', 1, type=int)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'agrs'
2018-05-09 17:01:16,635 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:60]
2018-05-09 17:01:57,683 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:60]
