2018-05-04 16:03:39,900 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:61]
2018-05-04 16:05:19,373 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:60]
2018-05-04 19:06:34,144 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:60]
2018-05-04 19:07:00,580 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:60]
2018-05-04 19:07:14,781 ERROR: Exception on /edit_profile [POST] [in /home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/krupni/microblog/app1/routes.py", line 101, in edit_profile
    if form.validate_on_submit():
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/krupni/microblog/app1/forms.py", line 48, in validate_username
    if username.data != original_username:
NameError: name 'original_username' is not defined
2018-05-04 19:08:17,504 ERROR: Exception on /edit_profile [POST] [in /home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/krupni/microblog/app1/routes.py", line 101, in edit_profile
    if form.validate_on_submit():
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/krupni/microblog/app1/forms.py", line 48, in validate_username
    if username.data != original_username:
NameError: name 'original_username' is not defined
2018-05-04 19:09:16,168 ERROR: Exception on /edit_profile [POST] [in /home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/krupni/microblog/app1/routes.py", line 101, in edit_profile
    if form.validate_on_submit():
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/krupni/microblog/app1/forms.py", line 48, in validate_username
    if username.data != original_username:
NameError: name 'original_username' is not defined
2018-05-04 19:09:35,585 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:60]
2018-05-04 19:09:42,595 ERROR: Exception on /edit_profile [POST] [in /home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/krupni/microblog/app1/routes.py", line 101, in edit_profile
    if form.validate_on_submit():
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/krupni/microblog/app1/forms.py", line 48, in validate_username
    if username.data != original_username:
NameError: name 'original_username' is not defined
