2018-06-05 10:12:04,704 ERROR: Exception on /index [GET] [in /home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/krupni/microblog/app1/main/routes.py", line 55, in index
    prev_url=prev_url)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/krupni/microblog/app1/templates/main/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: base.html
2018-06-05 10:14:03,230 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:90]
