2018-05-11 16:20:54,874 ERROR: Exception on /reset_password_request [POST] [in /home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/krupni/microblog/app1/routes.py", line 185, in reset_password_request
    send_password_reset_email(user)
  File "/home/krupni/microblog/app1/email.py", line 28, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token)
  File "/home/krupni/microblog/app1/email.py", line 19, in send_email
    mail.send(msg)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib64/python3.5/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python3.5/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python3.5/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib64/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib64/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2018-05-11 16:32:57,808 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:64]
2018-05-11 16:47:13,086 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:64]
2018-05-11 16:49:35,742 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:64]
2018-05-11 16:54:42,900 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:64]
2018-05-11 16:59:48,262 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:64]
2018-05-11 17:08:42,444 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:64]
2018-05-11 17:09:04,419 ERROR: Exception on /reset_password_request [POST] [in /home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/krupni/microblog/app1/routes.py", line 185, in reset_password_request
    send_password_reset_email(user)
  File "/home/krupni/microblog/app1/email.py", line 28, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token)
  File "/home/krupni/microblog/app1/email.py", line 18, in send_email
    Thread(target=send_async_email, args=(app,msg)).start()
NameError: name 'Thread' is not defined
2018-05-11 17:09:26,207 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:64]
2018-05-11 17:09:47,365 ERROR: Exception on /reset_password_request [POST] [in /home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/krupni/microblog/venv/lib64/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/krupni/microblog/app1/routes.py", line 185, in reset_password_request
    send_password_reset_email(user)
  File "/home/krupni/microblog/app1/email.py", line 28, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token)
  File "/home/krupni/microblog/app1/email.py", line 18, in send_email
    Thread(target=send_async_email, args=(app,msg)).start()
NameError: name 'Thread' is not defined
2018-05-11 17:10:01,829 INFO: Microblog startup [in /home/krupni/microblog/app1/__init__.py:64]
